# 1. Աρχնական բազան՝ օգտագործում ենք PHP CLI image-ը
FROM php:8.2-cli

# 2. Աշխատանքի պանակ (տեղը, որտեղ տեղադրելու ենք Laravel-ը)
WORKDIR /var/www/html

# 3. Սովորական dependency-ները, որոնք անհրաժեշտ են Laravel-ին
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    curl \
    git \
    vim

# 4. PHP ընդլայնումներ, որոնք անհրաժեշտ են Laravel-ի համար
RUN docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd

# 5. Composer-ը կոգցելու ենք որպես image
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# 6. Թույլ ենք տալիս՝ կարդալ և գրավել տվյալները
COPY . /var/www/html

# 7. Laravel dependencies (composer install)
RUN composer install --no-dev --optimize-autoloader

# 8. Պաշտոնական permission-ներ՝ storage-ի համար
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html/storage

# 9. Պորտի բացում
EXPOSE 8000

# 10. Laravel start command
CMD php artisan serve --host=0.0.0.0 --port=8000
